 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author KhangCao
 */
public class frmMain extends javax.swing.JFrame {

    /** Creates new form frmMain */
    public frmMain() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabQuanLy = new javax.swing.JTabbedPane();
        pnlQLDiem = new javax.swing.JPanel();
        pnlhinhnen = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        pnlnguoidung = new javax.swing.JPanel();
        txtchao = new javax.swing.JLabel();
        lblnguoidung = new javax.swing.JLabel();
        lblhinhnen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniChangePassword = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        mnuedit = new javax.swing.JMenu();
        mnuQLSinhVien = new javax.swing.JMenu();
        mniXemDanhSach = new javax.swing.JMenuItem();
        mnuQLDiem = new javax.swing.JMenu();
        mniNhapDiem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlhinhnen.setLayout(null);

        btnDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_system-log-out_118796 (1).png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        pnlhinhnen.add(btnDangXuat);
        btnDangXuat.setBounds(120, 130, 140, 60);

        btnDoiMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        btnDoiMatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock.png"))); // NOI18N
        btnDoiMatKhau.setText("Đổi Mật Khẩu");
        btnDoiMatKhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });
        pnlhinhnen.add(btnDoiMatKhau);
        btnDoiMatKhau.setBounds(460, 130, 150, 60);

        pnlnguoidung.setBackground(new java.awt.Color(255, 255, 255));

        txtchao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtchao.setText("Chào :");

        lblnguoidung.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlnguoidungLayout = new javax.swing.GroupLayout(pnlnguoidung);
        pnlnguoidung.setLayout(pnlnguoidungLayout);
        pnlnguoidungLayout.setHorizontalGroup(
            pnlnguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnguoidungLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(txtchao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblnguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        pnlnguoidungLayout.setVerticalGroup(
            pnlnguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlnguoidungLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlnguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtchao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlhinhnen.add(pnlnguoidung);
        pnlnguoidung.setBounds(20, 20, 760, 60);

        lblhinhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/giaodienchinh2.jpg"))); // NOI18N
        pnlhinhnen.add(lblhinhnen);
        lblhinhnen.setBounds(-90, 0, 900, 610);

        javax.swing.GroupLayout pnlQLDiemLayout = new javax.swing.GroupLayout(pnlQLDiem);
        pnlQLDiem.setLayout(pnlQLDiemLayout);
        pnlQLDiemLayout.setHorizontalGroup(
            pnlQLDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlhinhnen, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );
        pnlQLDiemLayout.setVerticalGroup(
            pnlQLDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlhinhnen, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        tabQuanLy.addTab("Giao diện Chính", pnlQLDiem);

        mnuFile.setText("File");

        mniChangePassword.setText("Đổi mật khẩu");
        mniChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChangePasswordActionPerformed(evt);
            }
        });
        mnuFile.add(mniChangePassword);

        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuFile.add(mniDangXuat);

        jMenuBar1.add(mnuFile);

        mnuedit.setText("Edit");
        jMenuBar1.add(mnuedit);

        mnuQLSinhVien.setText("Quản lý sinh viên");

        mniXemDanhSach.setText("Xem danh sách ");
        mnuQLSinhVien.add(mniXemDanhSach);

        jMenuBar1.add(mnuQLSinhVien);

        mnuQLDiem.setText("Quản lý điểm");

        mniNhapDiem.setText("Nhập điểm");
        mnuQLDiem.add(mniNhapDiem);

        jMenuBar1.add(mnuQLDiem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabQuanLy)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabQuanLy)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblnguoidung.setText(BLL.Register.user.getFullname());
        if(frmLogin.quyen.equals("quantri")){
            pnlNhanVien pnlQLNV = new pnlNhanVien();
            pnlLuong pnlLuong = new pnlLuong();
            pnlPhongBan pnlPhongBan = new pnlPhongBan();
            pnlListUser pnlListUser = new pnlListUser();
            tabQuanLy.add("Quản lý NV",pnlQLNV);
            tabQuanLy.add("Quản lý Lương",pnlLuong);
            tabQuanLy.add("Quản lý PhongBan",pnlPhongBan);
            tabQuanLy.add("Quản lý Users",pnlListUser);
            BLL.BLLNV.LayDuLieu(pnlQLNV.tblNhanVien);
            BLL.BLLLuong.LayDuLieu(pnlLuong.tblLuong);
            BLL.BLLPhongBan.LayDuLieu(pnlPhongBan.tblPhongBan);
            BLL.BLLUser.DoDuLieu(pnlListUser.tblNguoiDung);
            tabQuanLy.setEnabledAt(0, true);
        }
        //Kiểm tra quyền của người vừa đăng nhập
        else if(frmLogin.quyen.equals("giangvien")){
            pnlNhanVien pnlQLNV = new pnlNhanVien();
            pnlPhongBan pnlPhongBan = new pnlPhongBan();
            tabQuanLy.add("Quản lý NV",pnlQLNV);
            tabQuanLy.add("Quản lý PhongBan",pnlPhongBan);
            BLL.BLLNV.LayDuLieu(pnlQLNV.tblNhanVien);
            BLL.BLLPhongBan.LayDuLieu(pnlPhongBan.tblPhongBan);
            tabQuanLy.setEnabledAt(0, true);
        }else if(frmLogin.quyen.equals("daotao")){
            pnlNhanVien pnlQLNV = new pnlNhanVien();
            pnlLuong pnlLuong = new pnlLuong();
            tabQuanLy.add("Quản lý NV",pnlQLNV);
            tabQuanLy.add("Quản lý Lương",pnlLuong);
            BLL.BLLNV.LayDuLieu(pnlQLNV.tblNhanVien);
            BLL.BLLLuong.LayDuLieu(pnlLuong.tblLuong);
            tabQuanLy.setEnabledAt(0, true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        this.dispose();
        frmLogin frm = new frmLogin();
        frm.setVisible(true);
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChangePasswordActionPerformed
        this.dispose();
        frmChangePassword frm = new frmChangePassword();
        frm.setVisible(true);
    }//GEN-LAST:event_mniChangePasswordActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.dispose();
        frmLogin frm = new frmLogin();
        frm.setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        this.dispose();
        frmChangePassword frm = new frmChangePassword();
        frm.setVisible(true);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblhinhnen;
    private javax.swing.JLabel lblnguoidung;
    private javax.swing.JMenuItem mniChangePassword;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniNhapDiem;
    private javax.swing.JMenuItem mniXemDanhSach;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuQLDiem;
    private javax.swing.JMenu mnuQLSinhVien;
    private javax.swing.JMenu mnuedit;
    private javax.swing.JPanel pnlQLDiem;
    private javax.swing.JPanel pnlhinhnen;
    private javax.swing.JPanel pnlnguoidung;
    private javax.swing.JTabbedPane tabQuanLy;
    private javax.swing.JLabel txtchao;
    // End of variables declaration//GEN-END:variables

}
