/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Khang Cao
 */
public class jdlMHChao extends javax.swing.JDialog {
    int index;
    /**
     * Creates new form jdlWelcome
     */
    public jdlMHChao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Start();
    }
    private void Start() {
        pgbLoading.setStringPainted(true);
        Timer t = new Timer(8, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                index += 1;
                pgbLoading.setValue(index);
                if (index == 300) {
                    ((Timer) ae.getSource()).stop();
                    jdlMHChao.this.dispose();
                    ShowjdlDangNhap();
                }
            }
        });
        t.start();
    }
    void ShowjdlDangNhap() {
        this.dispose();
        frmLogin frm = new frmLogin();
        frm.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlnen = new javax.swing.JPanel();
        lblphanmemquanlynhanvien = new javax.swing.JLabel();
        pgbLoading = new javax.swing.JProgressBar();
        lblhinhnen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Giao Diện Khởi Động");
        setUndecorated(true);

        pnlnen.setLayout(null);

        lblphanmemquanlynhanvien.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblphanmemquanlynhanvien.setForeground(new java.awt.Color(255, 255, 255));
        lblphanmemquanlynhanvien.setText("Phần Mềm Quản Lý Nhân Sự");
        pnlnen.add(lblphanmemquanlynhanvien);
        lblphanmemquanlynhanvien.setBounds(280, 60, 470, 50);

        pgbLoading.setBackground(new java.awt.Color(255, 255, 255));
        pgbLoading.setForeground(new java.awt.Color(255, 255, 255));
        pgbLoading.setMaximum(250);
        pgbLoading.setToolTipText("");
        pgbLoading.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        pgbLoading.setFocusCycleRoot(true);
        pnlnen.add(pgbLoading);
        pgbLoading.setBounds(30, 504, 890, 6);

        lblhinhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nenkhoidong3.jpg"))); // NOI18N
        pnlnen.add(lblhinhnen);
        lblhinhnen.setBounds(-10, -10, 1000, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlnen, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlnen, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlMHChao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlMHChao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlMHChao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlMHChao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlMHChao dialog = new jdlMHChao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblhinhnen;
    private javax.swing.JLabel lblphanmemquanlynhanvien;
    private javax.swing.JProgressBar pgbLoading;
    private javax.swing.JPanel pnlnen;
    // End of variables declaration//GEN-END:variables
}
