/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author KhangCao
 */
public class jdlRegister extends javax.swing.JDialog {

    /**
     * Creates new form jdlRegister
     */
    public jdlRegister(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFullName = new javax.swing.JTextField();
        lblFullName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        cbbRole = new javax.swing.JComboBox<>();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblRetypePassword = new javax.swing.JLabel();
        txtRePassword = new javax.swing.JPasswordField();
        chkDieuKhoan = new javax.swing.JCheckBox();
        btnRegister = new javax.swing.JButton();
        lbldangnhap = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblhinhnen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtFullName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFullName);
        txtFullName.setBounds(320, 130, 230, 30);

        lblFullName.setBackground(new java.awt.Color(255, 255, 255));
        lblFullName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(255, 255, 255));
        lblFullName.setText("Họ và tên :");
        jPanel1.add(lblFullName);
        lblFullName.setBounds(200, 140, 100, 22);

        lblUsername.setBackground(new java.awt.Color(255, 255, 255));
        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Tên đăng nhập :");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(170, 190, 120, 20);

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email :");
        jPanel1.add(lblEmail);
        lblEmail.setBounds(240, 240, 50, 20);

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtUsername);
        txtUsername.setBounds(320, 180, 230, 30);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtEmail);
        txtEmail.setBounds(320, 230, 230, 30);

        lblRole.setBackground(new java.awt.Color(255, 255, 255));
        lblRole.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setText("Quyền :");
        jPanel1.add(lblRole);
        lblRole.setBounds(230, 290, 60, 20);

        cbbRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "quantri", "daotao", "giangvien" }));
        jPanel1.add(cbbRole);
        cbbRole.setBounds(320, 280, 230, 30);

        lblPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Mật khẩu :");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(210, 340, 80, 20);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtPassword);
        txtPassword.setBounds(320, 330, 230, 30);

        lblRetypePassword.setBackground(new java.awt.Color(255, 255, 255));
        lblRetypePassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblRetypePassword.setForeground(new java.awt.Color(255, 255, 255));
        lblRetypePassword.setText("Nhập lại mật khẩu :");
        jPanel1.add(lblRetypePassword);
        lblRetypePassword.setBounds(150, 390, 140, 20);

        txtRePassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtRePassword);
        txtRePassword.setBounds(320, 380, 230, 30);

        chkDieuKhoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkDieuKhoan.setForeground(new java.awt.Color(255, 255, 255));
        chkDieuKhoan.setText("Đồng ý với các điều khoản");
        chkDieuKhoan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkDieuKhoanItemStateChanged(evt);
            }
        });
        jPanel1.add(chkDieuKhoan);
        chkDieuKhoan.setBounds(320, 430, 200, 25);

        btnRegister.setBackground(new java.awt.Color(153, 255, 153));
        btnRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegister.setText("Đăng ký");
        btnRegister.setEnabled(false);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister);
        btnRegister.setBounds(360, 490, 130, 40);

        lbldangnhap.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbldangnhap.setForeground(new java.awt.Color(255, 255, 255));
        lbldangnhap.setText("Đăng Ký");
        jPanel1.add(lbldangnhap);
        lbldangnhap.setBounds(70, 40, 200, 50);

        lblMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMin.setForeground(new java.awt.Color(255, 255, 255));
        lblMin.setText("-");
        lblMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
        });
        jPanel1.add(lblMin);
        lblMin.setBounds(720, 20, 10, 29);

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel1.add(lblClose);
        lblClose.setBounds(750, 20, 16, 29);

        lblhinhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nenkhoidong1.jpg"))); // NOI18N
        lblhinhnen.setText("jLabel1");
        jPanel1.add(lblhinhnen);
        lblhinhnen.setBounds(0, 0, 820, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String fullname = txtFullName.getText();
        String username = txtUsername.getText();
        String role = cbbRole.getSelectedItem().toString();
        String email = txtEmail.getText();
        String password = String.valueOf(txtPassword.getPassword());
        String repassword = String.valueOf(txtRePassword.getPassword());
        
        boolean kq = BLL.Register.KiemTra(fullname, username, role, email, password, repassword);
        if(kq){
            ThongBao.ThongBao("Đăng ký người dùng thành công!", "Thông báo");
            this.dispose();
        }else{
            
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void chkDieuKhoanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkDieuKhoanItemStateChanged
       if(chkDieuKhoan.isSelected()){
           btnRegister.setEnabled(true);
       }else{
           btnRegister.setEnabled(false);
       }
    }//GEN-LAST:event_chkDieuKhoanItemStateChanged

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked

    }//GEN-LAST:event_lblMinMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked

        int NutBam = JOptionPane.showConfirmDialog(this,
                 "Bạn có chắc chắn muốn thoát không",
                 "Xác nhận thoát chương trình",
                 JOptionPane.OK_CANCEL_OPTION);
        if (NutBam == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlRegister dialog = new jdlRegister(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cbbRole;
    private javax.swing.JCheckBox chkDieuKhoan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRetypePassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lbldangnhap;
    private javax.swing.JLabel lblhinhnen;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
