/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLLNV;
import DTO.NhanVien;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author KhangCao
 */
public class pnlPhongBan extends javax.swing.JPanel {

    private NhanVien nhanVien;

    /**
     * Creates new form pnlDG
     */
    public pnlPhongBan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jDialog1 = new javax.swing.JDialog();
        scpNhanVien = new javax.swing.JScrollPane();
        tblPhongBan = new javax.swing.JTable();
        pnlDieuHuong = new javax.swing.JPanel();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        txttimkiem = new javax.swing.JTextField();
        btntk = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblcmnd = new javax.swing.JLabel();
        txtTenPB = new javax.swing.JTextField();
        txtdc = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        lblQuanLyPhongBan = new javax.swing.JLabel();
        lblHinhNen = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 204, 204));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        tblPhongBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Phòng Bàn", "Địa chỉ", "SDT", "Mã Phòng Ban"
            }
        ));
        tblPhongBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongBanMouseClicked(evt);
            }
        });
        scpNhanVien.setViewportView(tblPhongBan);
        if (tblPhongBan.getColumnModel().getColumnCount() > 0) {
            tblPhongBan.getColumnModel().getColumn(0).setMinWidth(10);
            tblPhongBan.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        add(scpNhanVien);
        scpNhanVien.setBounds(10, 389, 773, 197);

        pnlDieuHuong.setBackground(new java.awt.Color(255, 255, 255));
        pnlDieuHuong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnthem.setBackground(new java.awt.Color(255, 255, 255));
        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_add.png"))); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setBackground(new java.awt.Color(255, 255, 255));
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_delete.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btntk.setText("Tìm kiếm");
        btntk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntkActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/config.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDieuHuongLayout = new javax.swing.GroupLayout(pnlDieuHuong);
        pnlDieuHuong.setLayout(pnlDieuHuongLayout);
        pnlDieuHuongLayout.setHorizontalGroup(
            pnlDieuHuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDieuHuongLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btntk, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        pnlDieuHuongLayout.setVerticalGroup(
            pnlDieuHuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDieuHuongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDieuHuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnxoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDieuHuongLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnlDieuHuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btntk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttimkiem, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(pnlDieuHuongLayout.createSequentialGroup()
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        add(pnlDieuHuong);
        pnlDieuHuong.setBounds(10, 315, 773, 63);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTenNhanVien.setText("Tên Phòng Ban :");

        lblDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDiaChi.setText("Địa chỉ :");

        lblcmnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblcmnd.setText("SDT :");
        lblcmnd.setToolTipText("");

        txtsdt.setToolTipText("");

        lblQuanLyPhongBan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblQuanLyPhongBan.setForeground(new java.awt.Color(102, 102, 102));
        lblQuanLyPhongBan.setText("Quản Lý Phòng Ban");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDiaChi)
                            .addComponent(lblTenNhanVien))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTenPB, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(lblcmnd)
                                .addGap(18, 18, 18)
                                .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(lblQuanLyPhongBan)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblQuanLyPhongBan)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblcmnd)
                        .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTenNhanVien)
                        .addComponent(txtTenPB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi)
                    .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(13, 13, 770, 290);

        lblHinhNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nenkhoidong3.jpg"))); // NOI18N
        lblHinhNen.setText("jLabel2");
        add(lblHinhNen);
        lblHinhNen.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        String TenPB = txtTenPB.getText();
        String DiaChi = txtdc.getText();
        String SDT = txtsdt.getText();
        boolean kq = BLL.BLLPhongBan.KiemTra(SDT,TenPB,DiaChi);
            if (kq) {
            BLL.BLLPhongBan.LayDuLieu(tblPhongBan);
            }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btntkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntkActionPerformed
        String tuKhoa = txttimkiem.getText();
        BLL.BLLPhongBan.TimDuLieu(tblPhongBan, tuKhoa);
    }//GEN-LAST:event_btntkActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
      int kq = JOptionPane.showConfirmDialog(new JFrame(), "Bạn có chắc chắn xóa không?", "Thông báo xác nhận",JOptionPane.YES_NO_OPTION);
        if(kq == JOptionPane.YES_OPTION){
            //Thực hiện xóa
            //Lấy các dòng được chọn
            int cacdong[] = tblPhongBan.getSelectedRows();
            for(int i = cacdong.length-1; i >= 0; i--){
               String tenDG = tblPhongBan.getValueAt(cacdong[i],1).toString();
               DAO.DAOPhongBan.Delete(tenDG);
            }
            BLL.BLLPhongBan.LayDuLieu(tblPhongBan);
        }
    }//GEN-LAST:event_btnxoaActionPerformed
    public static String DocGiaEdit;
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int soDongDuocChon = tblPhongBan.getSelectedRowCount();
        if(soDongDuocChon < 1){
            ThongBao.ThongBao("Bạn cần chon 1 dòng để sửa", "Thông báo");
            return;
        }
            String tenPB = txtTenPB.getText();
            String diaChi = txtdc.getText();
            String SDT = txtsdt.getText();
            
            int viTri=tblPhongBan.getSelectedRow();
            String maPB = tblPhongBan.getValueAt(viTri,4).toString();
            boolean kq = BLL.BLLPhongBan.KiemTraSua(SDT, tenPB, diaChi,maPB);
            if (kq) {
            BLL.BLLPhongBan.LayDuLieu(tblPhongBan);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void tblPhongBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongBanMouseClicked
         if(tblPhongBan.getSelectedRowCount()>=1){
          btnxoa.setEnabled(true); 
        }
        if(tblPhongBan.getSelectedRowCount()>=1){
            btnSua.setEnabled(true);
            // lấy vị trí đc chọn
            int viTri = tblPhongBan.getSelectedRow();
            txtTenPB.setText(tblPhongBan.getValueAt(viTri,1).toString());
            txtdc.setText(tblPhongBan.getValueAt(viTri, 2).toString());
            txtsdt.setText(tblPhongBan.getValueAt(viTri, 3).toString());
        }else{ 
            btnSua.setEnabled(false);
        }
    }//GEN-LAST:event_tblPhongBanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntk;
    private javax.swing.JButton btnxoa;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblHinhNen;
    private javax.swing.JLabel lblQuanLyPhongBan;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblcmnd;
    private javax.swing.JPanel pnlDieuHuong;
    private javax.swing.JScrollPane scpNhanVien;
    public javax.swing.JTable tblPhongBan;
    private javax.swing.JTextField txtTenPB;
    private javax.swing.JTextField txtdc;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
